steps:

  #build and push native image
  - id: 'docker-build'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/realworld-api-quarkus:$COMMIT_SHA', '.' ]

  - id: 'docker-push'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/realworld-api-quarkus:$COMMIT_SHA']
    waitFor:
      - "quarkus-build"

  - id: 'cloud-run-deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'realworld-conduit-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/realworld-api-quarkus:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
    waitFor:
      - "quarkus-build"