DELETE http://localhost:8080/api/profiles/celeb_u1584108106/follow
Accept: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2MmNhNDc3Ni02MjYxLTRjNTItYWZkOS03ZGYyOTFjNmJkYzMiLCJST0xFUyI6WyJVU0VSIl0sImlzcyI6InVzZXJzLXNlcnZpY2UiLCJjb21wbGVtZW50YXJ5LXN1YnNjcmlwdGlvbiI6IjFjNDM2NjQyLTJkMWYtNGFiOS05YzQ5LTI3MzlmNmRlZDYzMSIsImV4cCI6MTU4NDEwOTAzMCwiaWF0IjoxNTg0MTA4NDMwfQ.hZf15iRVaYT0NMeAdaAFbuAE8ugFyr9LLbGHlcnmHEQBwKqukdkI7vitnmE6qMfhnA7cnx1rED3ut09X-HZSCA

###
POST http://localhost:8080/api/profiles/celeb_u1584108106/follow
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2MmNhNDc3Ni02MjYxLTRjNTItYWZkOS03ZGYyOTFjNmJkYzMiLCJST0xFUyI6WyJVU0VSIl0sImlzcyI6InVzZXJzLXNlcnZpY2UiLCJjb21wbGVtZW50YXJ5LXN1YnNjcmlwdGlvbiI6IjFjNDM2NjQyLTJkMWYtNGFiOS05YzQ5LTI3MzlmNmRlZDYzMSIsImV4cCI6MTU4NDEwOTAzMCwiaWF0IjoxNTg0MTA4NDMwfQ.hZf15iRVaYT0NMeAdaAFbuAE8ugFyr9LLbGHlcnmHEQBwKqukdkI7vitnmE6qMfhnA7cnx1rED3ut09X-HZSCA

{}

###
#Values used in the postman collection
#
#USERNAME=u1583928853
#EMAIL=u1583928853@mail.com
#PASSWORD=password

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "user": {
    "email": "u1583928853@mail.com",
    "password": "password",
    "username": "u1583928853"
  }
}}

###

POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "u1583928853@mail.com",
    "password": "password"
  }
}
###



